{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 36,
   "id": "f5e99c29",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Importing necessary libraries\n",
    "from selenium import webdriver\n",
    "from selenium.webdriver.chrome.service import Service\n",
    "from webdriver_manager.chrome import ChromeDriverManager\n",
    "from selenium.webdriver.support.ui import WebDriverWait\n",
    "from selenium.webdriver.support import expected_conditions as EC\n",
    "from selenium.common.exceptions import NoSuchElementException\n",
    "from selenium.webdriver.common.by import By\n",
    "import time\n",
    "import pandas as pd\n",
    "\n",
    "# Function to scroll down the page to load more videos\n",
    "def scroll_down_page(driver):\n",
    "    scroll_position = 0\n",
    "    while True:\n",
    "        driver.execute_script(\"window.scrollTo(0, {});\".format(scroll_position))\n",
    "        time.sleep(1)\n",
    "        scroll_position += 500\n",
    "        if scroll_position >= driver.execute_script(\"return document.body.scrollHeight\"):\n",
    "            break\n",
    "\n",
    "# Function to extract video details\n",
    "def extract_video_details(video):\n",
    "    try:\n",
    "        # Extracting title\n",
    "        title_element = video.find_element(By.XPATH, './/*[@id=\"video-title\"]/yt-formatted-string').text\n",
    "    except NoSuchElementException:\n",
    "        title_element = \"N/A\"\n",
    "\n",
    "    try:\n",
    "        # Extracting views \n",
    "        views = video.find_element(By.XPATH, './/div[@id=\"metadata-line\"]//span[1]').text      \n",
    "    except NoSuchElementException:\n",
    "        views = \"N/A\"\n",
    "\n",
    "    try:\n",
    "        # Extracting upload time\n",
    "        date = video.find_element(By.XPATH, './/div[@id=\"metadata-line\"]//span[2]').text\n",
    "    except NoSuchElementException:\n",
    "        date = \"N/A\"\n",
    "\n",
    "    try:\n",
    "        # Extracting channel name\n",
    "        channel = video.find_element(By.XPATH, './/a[@class=\"yt-simple-endpoint style-scope yt-formatted-string\"]').text\n",
    "    except NoSuchElementException:\n",
    "        channel = \"N/A\"\n",
    "\n",
    "    try:\n",
    "        # Extracting descriptions\n",
    "        desc = video.find_element(By.XPATH, './/yt-formatted-string[@class=\"metadata-snippet-text style-scope ytd-video-renderer\"]').text\n",
    "    except NoSuchElementException:\n",
    "        desc = \"N/A\"\n",
    "\n",
    "    try:\n",
    "        # Extracting thumbnail\n",
    "        thumbnail = video.find_element(By.XPATH, './/img[@class=\"yt-core-image yt-core-image--fill-parent-height yt-core-image--fill-parent-width yt-core-image--content-mode-scale-aspect-fill yt-core-image--loaded\"]').get_attribute('src')\n",
    "    except NoSuchElementException:\n",
    "        thumbnail = \"N/A\"\n",
    "\n",
    "    try:\n",
    "        # Extracting video url\n",
    "        url = video.find_element(By.XPATH, './/a[@id=\"video-title\"]').get_attribute('href')\n",
    "    except NoSuchElementException:\n",
    "        url = \"N/A\"\n",
    "\n",
    "    return {\n",
    "        'Title': title_element,\n",
    "        'Views': views,\n",
    "        'Upload Time': date,\n",
    "        'Channel': channel,\n",
    "        'Description': desc,\n",
    "        'Thumbnail': thumbnail,\n",
    "        'URL': url\n",
    "    }\n",
    "\n",
    "# Main function\n",
    "def main():\n",
    "    # Setting up the Chrome driver\n",
    "    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))\n",
    "    driver.get(\"https://www.youtube.com/results?search_query=top_pakistan_youtuber\")\n",
    "    time.sleep(10)\n",
    "\n",
    "    # Scrolling down the page to load more videos\n",
    "    scroll_down_page(driver)\n",
    "\n",
    "    # Get all video elements\n",
    "    video_divs = driver.find_elements(By.XPATH, '//div[@id=\"dismissible\"]')\n",
    "\n",
    "    # Extracting details for each video\n",
    "    video_details = [extract_video_details(video) for video in video_divs]\n",
    "\n",
    "    # Creating a DataFrame from the extracted details\n",
    "    df = pd.DataFrame(video_details)\n",
    "\n",
    "    # Saving the DataFrame to a CSV file\n",
    "    df.to_csv('youtube_videos.csv', index=False)\n",
    "\n",
    "    # Closing the driver\n",
    "    driver.quit()\n",
    "\n",
    "# Calling the main function\n",
    "if __name__ == \"__main__\":\n",
    "    main()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 34,
   "id": "a7963e52",
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'df' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[34], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[43mdf\u001b[49m\n",
      "\u001b[0;31mNameError\u001b[0m: name 'df' is not defined"
     ]
    }
   ],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "0b8d0dc6",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "eca2a6d5",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "40"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "id": "fbad1953",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Top 10 Pakistani YouTubers | Top Pakistani YouTubers 2022 | Anas Tv\n",
      "Top 10 Pakistani YouTubers | Top Pakistani YouTubers 2022 | Anas Tv \n",
      " 142K views \n",
      " 1 year ago \n",
      "  \n",
      " Assalam O Alaikum!! Iss Video Main Aapko Top 10 Pakistani YouTubers ke Barey main Batayngy K Pakistan K Top YouTubers ... \n",
      " https://i.ytimg.com/vi/XiKd2qbZfrM/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDOpbv1gX2JIpbTqfPeWIoU17lS8g \n",
      " https://www.youtube.com/watch?v=XiKd2qbZfrM&pp=ygUVdG9wX3Bha2lzdGFuX3lvdXR1YmVy\n",
      "Top 20 Pakistani 🇵🇰 | YouTubers Vloggers 😍 | 3D Comparison Video 2024\n",
      "Top 20 Pakistani 🇵🇰 | YouTubers Vloggers 😍 | 3D Comparison Video 2024 \n",
      " 173K views \n",
      " 3 months ago \n",
      "  \n",
      " Top 20 Pakistani | YouTubers Vloggers | 3D Comparison Video 2024 #duckybhai #maazsafder #sistrology #vlogging ... \n",
      " https://i.ytimg.com/vi/VB98JSF7CAw/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCk3VEbew269vC9ygw0cd1ZBosdSQ \n",
      " https://www.youtube.com/watch?v=VB98JSF7CAw&pp=ygUVdG9wX3Bha2lzdGFuX3lvdXR1YmVy\n",
      "N/A \n",
      " 717K views \n",
      " N/A \n",
      " N/A \n",
      " N/A \n",
      " https://i.ytimg.com/vi/BuG-PVsH1t8/hq720.jpg?sqp=-oaymwEdCJUDENAFSFXyq4qpAw8IARUAAIhCcAHAAQbQAQE=&rs=AOn4CLANsR4KIoPYbOmtb0KPDYUGJIn5HA \n",
      " N/A\n",
      "N/A \n",
      " 104K views \n",
      " N/A \n",
      " N/A \n",
      " N/A \n",
      " https://i.ytimg.com/vi/zsdDN0E0xL8/hq720.jpg?sqp=-oaymwEdCJUDENAFSFXyq4qpAw8IARUAAIhCcAHAAQbQAQE=&rs=AOn4CLCDzFx1HiItg-Dvjq6STehm3LFMBg \n",
      " N/A\n",
      "N/A \n",
      " 262K views \n",
      " N/A \n",
      " N/A \n",
      " N/A \n",
      " https://i.ytimg.com/vi/HggXr9Xcgag/hq720.jpg?sqp=-oaymwEdCJUDENAFSFXyq4qpAw8IARUAAIhCcAHAAQbQAQE=&rs=AOn4CLCkwoZV3SWZWVoGXxIUms_SxYORow \n",
      " N/A\n",
      "N/A \n",
      " 6.6M views \n",
      " N/A \n",
      " N/A \n",
      " N/A \n",
      " https://i.ytimg.com/vi/sLjjBT4VHug/hq720.jpg?sqp=-oaymwEdCJUDENAFSFXyq4qpAw8IARUAAIhCcAHAAQbQAQE=&rs=AOn4CLAoE-925GUR_Dk1aQn5xrQgbZH8PA \n",
      " N/A\n",
      "N/A \n",
      "  \n",
      " N/A \n",
      " N/A \n",
      " N/A \n",
      " N/A \n",
      " N/A\n",
      "N/A \n",
      "  \n",
      " N/A \n",
      " N/A \n",
      " N/A \n",
      " N/A \n",
      " N/A\n",
      "Top 10 Pakistani YouTubers Most Expensive Car | Ducky Bhai, Maaz Safder, Shehr Main Dihat, P4 Pakao\n",
      "Top 10 Pakistani YouTubers Most Expensive Car | Ducky Bhai, Maaz Safder, Shehr Main Dihat, P4 Pakao \n",
      " 141K views \n",
      " 1 month ago \n",
      "  \n",
      " Top 10 Pakistani YouTubers Most Expensive Car | Ducky Bhai, Maaz Safder, Shehr Main Dihat, P4 Pakao . . . #duckybhai ... \n",
      " https://i.ytimg.com/vi/sBoJhC0YTcI/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBQxyF7a2zQ5ZhVuvsmwdrUKhbWxA \n",
      " https://www.youtube.com/watch?v=sBoJhC0YTcI&pp=ygUVdG9wX3Bha2lzdGFuX3lvdXR1YmVy\n",
      "PAKISTAN Top. 1 UMP Player Vs MR ABU | Free Fire\n",
      "PAKISTAN Top. 1 UMP Player Vs MR ABU | Free Fire \n",
      " 119K views \n",
      " 4 months ago \n",
      "  \n",
      " PAKISTAN Top. 1 UMP Player Vs MR ABU | Free Fire I am a Free Fire Professional Player from Pakistan who uploads one tap ... \n",
      " https://i.ytimg.com/vi/sAiirhrfE-I/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDLgujJPJGNv8Y603KWtUsH5ij1Ow \n",
      " https://www.youtube.com/watch?v=sAiirhrfE-I&pp=ygUVdG9wX3Bha2lzdGFuX3lvdXR1YmVy\n",
      "N/A \n",
      " 997K views \n",
      " N/A \n",
      " N/A \n",
      " N/A \n",
      " https://i.ytimg.com/vi/YlgF19w9Y6E/oar2.jpg?sqp=-oaymwEdCJUDENAFSFWQAgHyq4qpAwwIARUAAIhCcAHAAQY=&rs=AOn4CLCNu13dC5NwgdT0zGEWsnmSXZTmxg \n",
      " N/A\n",
      "N/A \n",
      " 1.5M views \n",
      " N/A \n",
      " N/A \n",
      " N/A \n",
      " https://i.ytimg.com/vi/0zIHdFAQBMg/hq720.jpg?sqp=-oaymwEdCJUDENAFSFXyq4qpAw8IARUAAIhCcAHAAQbQAQE=&rs=AOn4CLBclsDw8-VYGcCGp8EUASXJbiD5-w \n",
      " N/A\n",
      "N/A \n",
      " 12M views \n",
      " N/A \n",
      " N/A \n",
      " N/A \n",
      " https://i.ytimg.com/vi/1iBRZ6UCIz8/hq720.jpg?sqp=-oaymwEdCJUDENAFSFXyq4qpAw8IARUAAIhCcAHAAQbQAQE=&rs=AOn4CLBvFx7NYFu9Vx1QcIcSDFsoQ2j1bA \n",
      " N/A\n",
      "N/A \n",
      " 32K views \n",
      " N/A \n",
      " N/A \n",
      " N/A \n",
      " https://i.ytimg.com/vi/cxczDjY6-_8/oardefault.jpg?sqp=-oaymwEdCJUDENAFSFWQAgHyq4qpAwwIARUAAIhCcAHAAQY=&rs=AOn4CLAKvvtfb5y6WrD5gTtUNRox86yaUg \n",
      " N/A\n",
      "N/A \n",
      "  \n",
      " N/A \n",
      " N/A \n",
      " N/A \n",
      " N/A \n",
      " N/A\n",
      "N/A \n",
      "  \n",
      " N/A \n",
      " N/A \n",
      " N/A \n",
      " N/A \n",
      " N/A\n",
      "2 CRORE Monthly Earning🫣😱 How Much Pakistani YouTubers Earns Monthly?\n",
      "2 CRORE Monthly Earning🫣😱 How Much Pakistani YouTubers Earns Monthly? \n",
      " 407K views \n",
      " 3 months ago \n",
      "  \n",
      " Welcome to this video, here you will learn how much Pakistani YouTubers Earn Monthly. Who is Earning 2 Crore from YouTube ? \n",
      " https://i.ytimg.com/vi/eN7VSs0siME/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBfYzqBNMEeCnk9uN4NxhAsKlXtxw \n",
      " https://www.youtube.com/watch?v=eN7VSs0siME&pp=ygUVdG9wX3Bha2lzdGFuX3lvdXR1YmVy\n",
      "Finally ! Revenge From Top Youtubers | Pakistani Community Power | Pubg Mobile | HOW BRAND\n",
      "Finally ! Revenge From Top Youtubers | Pakistani Community Power | Pubg Mobile | HOW BRAND \n",
      " 75K views \n",
      " 6 months ago \n",
      "  \n",
      " Like, Subscribe, Comment & Don't Forget To Press The Bell Icon #PUBGMNextStarProgram #PUBGMOBILE ... \n",
      " https://i.ytimg.com/vi/EYdl8Yn9UbM/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCxSGKfauziIWrSRpxLPGx6ZAS4Xw \n",
      " https://www.youtube.com/watch?v=EYdl8Yn9UbM&pp=ygUVdG9wX3Bha2lzdGFuX3lvdXR1YmVy\n",
      "1000 views ke kitne paise milte hain | youtube 1000 views ke kitne paise deta hai |YouTube Earnings|\n",
      "1000 views ke kitne paise milte hain | youtube 1000 views ke kitne paise deta hai |YouTube Earnings| \n",
      " 1.4M views \n",
      " 1 year ago \n",
      "  \n",
      " Is video mein apko btaunga k YouTube say 1000 views ke kitne paise milte hain Your searches youtube 1000 views ke kitne ... \n",
      " N/A \n",
      " https://www.youtube.com/watch?v=H9dkQk9lINE&pp=ygUVdG9wX3Bha2lzdGFuX3lvdXR1YmVy\n",
      "1000 views ke kitne paise milte hain | youtube 1000 views ke kitne paise deta hai |YouTube Earnings|\n",
      "1000 views ke kitne paise milte hain | youtube 1000 views ke kitne paise deta hai |YouTube Earnings| \n",
      " 1.4M views \n",
      " 1 year ago \n",
      "  \n",
      " Is video mein apko btaunga k YouTube say 1000 views ke kitne paise milte hain Your searches youtube 1000 views ke kitne ... \n",
      " N/A \n",
      " https://www.youtube.com/watch?v=H9dkQk9lINE&pp=ygUVdG9wX3Bha2lzdGFuX3lvdXR1YmVy\n",
      "Aizal Mery Sy Naraz Ho Gai || Haram Main Quran Pak Rakhwa Diye\n",
      "Aizal Mery Sy Naraz Ho Gai || Haram Main Quran Pak Rakhwa Diye \n",
      " 37K views \n",
      " 57 minutes ago \n",
      "  \n",
      " ZULQARNAIN : https://www.instagram.com/invites/con... KANWAL : https://instagram.com/kanwal.135?utm_... I Hope You Enjoyed ... \n",
      " N/A \n",
      " https://www.youtube.com/watch?v=c1QXDcvcArA&pp=ygUVdG9wX3Bha2lzdGFuX3lvdXR1YmVy\n",
      "Ghar chor ky kahan gai th ? Secret reveal kr diya | Hira Faisal | Sistrology\n",
      "Ghar chor ky kahan gai th ? Secret reveal kr diya | Hira Faisal | Sistrology \n",
      " 284K views \n",
      " 5 hours ago \n",
      "  \n",
      " I am a YouTube Creator Hira Faisal This is my Official Youtube Channel. Here you'll get my Vlogs, Shots & Skits. Kindly like ... \n",
      " N/A \n",
      " https://www.youtube.com/watch?v=SX--gxhSSpI&pp=ygUVdG9wX3Bha2lzdGFuX3lvdXR1YmVy\n",
      "EMERGENCY SHADI PY JANA PARA 😍 | Behno K Sath Funny Game Challenge 😂\n",
      "EMERGENCY SHADI PY JANA PARA 😍 | Behno K Sath Funny Game Challenge 😂 \n",
      " 375K views \n",
      " 4 hours ago \n",
      "  \n",
      " Don't forget to subscribe! Areeb Pervaiz▻ https://www.youtube.com/channel/UC1OttW11FcA2Szx8IGdBsHQ Susral Mai Shadi | In ... \n",
      " N/A \n",
      " https://www.youtube.com/watch?v=X7TL_xi8Q0I&pp=ygUVdG9wX3Bha2lzdGFuX3lvdXR1YmVy\n",
      "Top 5 Pakistani Youtubers | Top 5 Vloggers in Pakistani 2023 #vlog #vlogs\n",
      "Top 5 Pakistani Youtubers | Top 5 Vloggers in Pakistani 2023 #vlog #vlogs \n",
      " 100K views \n",
      " 9 months ago \n",
      "  \n",
      " Top 5 Pakistani Youtubers | Top 5 Vloggers in Pakistani 2023. ▻ For Copyright Matter, please Email us ... \n",
      " N/A \n",
      " https://www.youtube.com/watch?v=TZj0UMEbN_w&pp=ygUVdG9wX3Bha2lzdGFuX3lvdXR1YmVy\n",
      "Earnings of Top Pakistani YouTubers | 6X Formula\n",
      "Earnings of Top Pakistani YouTubers | 6X Formula \n",
      " 1.2M views \n",
      " 2 years ago \n",
      "  \n",
      " /Our Other Channels\\. KM YouTube: www.youtube.com/kmyoutubeofficial. /SOCIAL LINKS\\. Instagram ... \n",
      " N/A \n",
      " https://www.youtube.com/watch?v=opshtTXXqdQ&pp=ygUVdG9wX3Bha2lzdGFuX3lvdXR1YmVy\n",
      "Top 50 Most Subscribed YouTube Channels in Pakistan 2024\n",
      "Top 50 Most Subscribed YouTube Channels in Pakistan 2024 \n",
      " 6.3K views \n",
      " 4 months ago \n",
      "  \n",
      " As of my last knowledge update in Decembe 2023, I don't have real-time information, so the popularity of YouTubers may have ... \n",
      " N/A \n",
      " https://www.youtube.com/watch?v=zyC0rFoQfqU&pp=ygUVdG9wX3Bha2lzdGFuX3lvdXR1YmVy\n",
      "Top 50 Most Subscribed YouTube Channels in Pakistan 2024\n",
      "Top 50 Most Subscribed YouTube Channels in Pakistan 2024 \n",
      " 6.3K views \n",
      " 4 months ago \n",
      "  \n",
      " As of my last knowledge update in Decembe 2023, I don't have real-time information, so the popularity of YouTubers may have ... \n",
      " N/A \n",
      " https://www.youtube.com/watch?v=zyC0rFoQfqU&pp=ygUVdG9wX3Bha2lzdGFuX3lvdXR1YmVy\n",
      "Top 8 Best Pakistani Dramas In 2023 | HAR PAL GEO | HUM TV | ARY DIGITAL | MR NOMAN ALEEM\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Top 8 Best Pakistani Dramas In 2023 | HAR PAL GEO | HUM TV | ARY DIGITAL | MR NOMAN ALEEM \n",
      " 719K views \n",
      " 4 months ago \n",
      "  \n",
      " Here is the list of Top 8 Best Pakistani Dramas In 2023 | HAR PAL GEO | HUM TV | ARY DIGITAL | MR NOMAN ALEEM Follow Me ... \n",
      " N/A \n",
      " https://www.youtube.com/watch?v=vAeQCzhjwi4&pp=ygUVdG9wX3Bha2lzdGFuX3lvdXR1YmVy\n",
      "Trying Top 5 Pakistani Dishes\n",
      "Trying Top 5 Pakistani Dishes \n",
      " 218K views \n",
      " 3 months ago \n",
      "  \n",
      " Trying Top 5 Pakistani Dishes Maja aago bhaiya. \n",
      " N/A \n",
      " https://www.youtube.com/watch?v=nI0MJoK1gjk&pp=ygUVdG9wX3Bha2lzdGFuX3lvdXR1YmVy\n",
      "Monthly Earnings Of Top Pakistani Youtubers | Richest Pakistani Youtubers\n",
      "Monthly Earnings Of Top Pakistani Youtubers | Richest Pakistani Youtubers \n",
      " 26K views \n",
      " 1 year ago \n",
      "  \n",
      " Assalam o Alikum Friends I'm HAMZA. \"In this amazing video, we take a look at the top 10 richest YouTubers in pakistan. \n",
      " N/A \n",
      " https://www.youtube.com/watch?v=OX2E0i_IBng&pp=ygUVdG9wX3Bha2lzdGFuX3lvdXR1YmVy\n",
      "11 HOT NEW YouTube Channel Ideas for Pakistan\n",
      "11 HOT NEW YouTube Channel Ideas for Pakistan \n",
      " 748K views \n",
      " 1 year ago \n",
      "  \n",
      " KEY INFORMATION: # About Me: www.Chaiwala.com # PR Team: PR.Chaiwala.com # I'm Hiring: Jobs.Chaiwala.com # Get ... \n",
      " N/A \n",
      " https://www.youtube.com/watch?v=T6FIQR9bWGQ&pp=ygUVdG9wX3Bha2lzdGFuX3lvdXR1YmVy\n",
      "Top 5 Pakistani Pets Vloggers | Top 5 Pakistani Youtubers #vlog #pets #youtuber\n",
      "Top 5 Pakistani Pets Vloggers | Top 5 Pakistani Youtubers #vlog #pets #youtuber \n",
      " 312K views \n",
      " 3 months ago \n",
      "  \n",
      " Top 5 Pakistani Pets Vloggers | Top 5 Pakistani Youtubers #vlog #pets #youtuber Subscribe More Videos #top #youtuber ... \n",
      " N/A \n",
      " https://www.youtube.com/watch?v=jlGSgH9EGRA&pp=ygUVdG9wX3Bha2lzdGFuX3lvdXR1YmVy\n",
      "First Earnings of Top Pakistani YouTubers | Ft Mooroo, Ducky, Junaid, Nadir and more\n",
      "First Earnings of Top Pakistani YouTubers | Ft Mooroo, Ducky, Junaid, Nadir and more \n",
      " 218K views \n",
      " 2 years ago \n",
      "  \n",
      " Pakistani Youtubers and Their First Income? Ft Mooroo, Ducky, Junaid, Nadir, Video wali sarkar , Junaid Akram , Bekaar Films, ... \n",
      " N/A \n",
      " https://www.youtube.com/watch?v=i6Bhg_p4W1s&pp=ygUVdG9wX3Bha2lzdGFuX3lvdXR1YmVy\n",
      "Top 10 youtubers in Pakistan 2023 | Pakistan ka top 10 YouTube channel | Data! Status! & Information\n",
      "Top 10 youtubers in Pakistan 2023 | Pakistan ka top 10 YouTube channel | Data! Status! & Information \n",
      " 15K views \n",
      " 10 months ago \n",
      "  \n",
      " Top 10 youtubers in Pakistan 2023 | Pakistan ka top 10 YouTube channel | Data! Status! & Information Irfan Junejo: Irfan Junejo is ... \n",
      " N/A \n",
      " https://www.youtube.com/watch?v=3ytiXBQogOs&pp=ygUVdG9wX3Bha2lzdGFuX3lvdXR1YmVy\n",
      "Pakistan Top 15 Most Subscribed YouTube Channels in 2023\n",
      "Pakistan Top 15 Most Subscribed YouTube Channels in 2023 \n",
      " 30K views \n",
      " 1 year ago \n",
      "  \n",
      " Most Subscribed YouTube channel in Pakistan 2023 Top 15 Pakistani youtubers 2023 Most Subscribed YouTube channel in ... \n",
      " N/A \n",
      " https://www.youtube.com/watch?v=W56Zw7OpCl4&pp=ygUVdG9wX3Bha2lzdGFuX3lvdXR1YmVy\n",
      "TOP TEN ISLAMIC YOUTUBE CHANNELS IN PAKISTAN\n",
      "TOP TEN ISLAMIC YOUTUBE CHANNELS IN PAKISTAN \n",
      " 6.6K views \n",
      " 1 year ago \n",
      "  \n",
      " TOP TEN ISLAMIC YOUTUBE CHANNELS IN PAKISTAN 1. AJ OFFICIAL 2. THE ISLAMIC TEACHER 3. MOLANA TARIQ ... \n",
      " N/A \n",
      " https://www.youtube.com/watch?v=YFCjxy5f5Bg&pp=ygUVdG9wX3Bha2lzdGFuX3lvdXR1YmVy\n",
      "TOP 5 DANGEROUS PLAYERS IN PAKISTAN🇵🇰🔥\n",
      "TOP 5 DANGEROUS PLAYERS IN PAKISTAN🇵🇰🔥 \n",
      " 708K views \n",
      " 9 months ago \n",
      "  \n",
      " TOP 5 DANGEROUS PLAYERS IN PAKISTAN - para SAMSUNG A3,A5,A6,A7,J2,J5,J7,S5,S6,S7,S9,A10,A20,A30,A50 So ... \n",
      " N/A \n",
      " https://www.youtube.com/watch?v=iKpeaa2aFU8&pp=ygUVdG9wX3Bha2lzdGFuX3lvdXR1YmVy\n",
      "Top 10 Pakistani Youtubers | Top 10 Youtubers in Pakistan 2022 | Top Pakistani Youtubers 2022\n",
      "Top 10 Pakistani Youtubers | Top 10 Youtubers in Pakistan 2022 | Top Pakistani Youtubers 2022 \n",
      " 5.4K views \n",
      " 1 year ago \n",
      "  \n",
      " Top 10 Pakistani Youtubers | Top 10 Youtubers in Pakistan 2022 | Top Pakistani Youtubers 2022 this video may include searches ... \n",
      " N/A \n",
      " https://www.youtube.com/watch?v=W69jYo1BVJI&pp=ygUVdG9wX3Bha2lzdGFuX3lvdXR1YmVy\n",
      "Ishq Murshid - 2nd Last Episode 30 [𝐂𝐂] - 28 Apr 24 - [ Khurshid Fans, Master Paints & Mothercare ]\n",
      "Ishq Murshid - 2nd Last Episode 30 [𝐂𝐂] - 28 Apr 24 - [ Khurshid Fans, Master Paints & Mothercare ] \n",
      " 10M views \n",
      " 21 hours ago \n",
      "  \n",
      " Subscribe To HUM TV - https://bit.ly/Humtvpk Ishq Murshid - 2nd Last Episode 30 [CC] - 28 Apr 24 - Sponsored By Khurshid Fans ... \n",
      " N/A \n",
      " https://www.youtube.com/watch?v=QmJN-j60aLg&pp=ygUVdG9wX3Bha2lzdGFuX3lvdXR1YmVy\n",
      "Top Pakistani YouTubers ke sath kra dinner🤤🍽️\n",
      "Top Pakistani YouTubers ke sath kra dinner🤤🍽️ \n",
      " 223K views \n",
      " 1 year ago \n",
      "  \n",
      " Keep supporting guys we are near to 100k jldi se krado ✨✨ YouTubers ke sath dinner kia boht Maza ayi Be happy Must like ... \n",
      " N/A \n",
      " https://www.youtube.com/watch?v=F1-faWonEzo&pp=ygUVdG9wX3Bha2lzdGFuX3lvdXR1YmVy\n"
     ]
    }
   ],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "a598b89c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "N/A \n",
      " 223K views \n",
      " 1 year ago \n",
      " \n"
     ]
    }
   ],
   "source": [
    "print(title, '\\n', views, '\\n', date, '\\n', channel)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a0f53a63",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
